// <auto-generated />
namespace ASP.NET_MVC5_Bootstrap_3._3._4_LESS1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userinfo1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userinfo1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505231740136_userinfo1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
